// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/crypto_jobs.proto

package cryptojobsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetHash    string                 `protobuf:"bytes,1,opt,name=target_hash,json=targetHash,proto3" json:"target_hash,omitempty"`
	Charset       string                 `protobuf:"bytes,2,opt,name=charset,proto3" json:"charset,omitempty"`
	MinLength     uint32                 `protobuf:"varint,3,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	MaxLength     uint32                 `protobuf:"varint,4,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	ChunkSize     uint64                 `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_proto_crypto_jobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_jobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_crypto_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJobRequest) GetTargetHash() string {
	if x != nil {
		return x.TargetHash
	}
	return ""
}

func (x *CreateJobRequest) GetCharset() string {
	if x != nil {
		return x.Charset
	}
	return ""
}

func (x *CreateJobRequest) GetMinLength() uint32 {
	if x != nil {
		return x.MinLength
	}
	return 0
}

func (x *CreateJobRequest) GetMaxLength() uint32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *CreateJobRequest) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type CreateJobResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TotalCandidates uint64                 `protobuf:"varint,2,opt,name=total_candidates,json=totalCandidates,proto3" json:"total_candidates,omitempty"`
	TotalRanges     uint64                 `protobuf:"varint,3,opt,name=total_ranges,json=totalRanges,proto3" json:"total_ranges,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateJobResponse) Reset() {
	*x = CreateJobResponse{}
	mi := &file_proto_crypto_jobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobResponse) ProtoMessage() {}

func (x *CreateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_jobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobResponse.ProtoReflect.Descriptor instead.
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_crypto_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreateJobResponse) GetTotalCandidates() uint64 {
	if x != nil {
		return x.TotalCandidates
	}
	return 0
}

func (x *CreateJobResponse) GetTotalRanges() uint64 {
	if x != nil {
		return x.TotalRanges
	}
	return 0
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_proto_crypto_jobs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_jobs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_crypto_jobs_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TargetHash      string                 `protobuf:"bytes,2,opt,name=target_hash,json=targetHash,proto3" json:"target_hash,omitempty"`
	Charset         string                 `protobuf:"bytes,3,opt,name=charset,proto3" json:"charset,omitempty"`
	MinLength       uint32                 `protobuf:"varint,4,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	MaxLength       uint32                 `protobuf:"varint,5,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Plaintext       string                 `protobuf:"bytes,7,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	CompletedRanges uint64                 `protobuf:"varint,8,opt,name=completed_ranges,json=completedRanges,proto3" json:"completed_ranges,omitempty"`
	TotalRanges     uint64                 `protobuf:"varint,9,opt,name=total_ranges,json=totalRanges,proto3" json:"total_ranges,omitempty"`
	TotalCandidates uint64                 `protobuf:"varint,10,opt,name=total_candidates,json=totalCandidates,proto3" json:"total_candidates,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_proto_crypto_jobs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_jobs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_crypto_jobs_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobResponse) GetTargetHash() string {
	if x != nil {
		return x.TargetHash
	}
	return ""
}

func (x *GetJobResponse) GetCharset() string {
	if x != nil {
		return x.Charset
	}
	return ""
}

func (x *GetJobResponse) GetMinLength() uint32 {
	if x != nil {
		return x.MinLength
	}
	return 0
}

func (x *GetJobResponse) GetMaxLength() uint32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *GetJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetJobResponse) GetPlaintext() string {
	if x != nil {
		return x.Plaintext
	}
	return ""
}

func (x *GetJobResponse) GetCompletedRanges() uint64 {
	if x != nil {
		return x.CompletedRanges
	}
	return 0
}

func (x *GetJobResponse) GetTotalRanges() uint64 {
	if x != nil {
		return x.TotalRanges
	}
	return 0
}

func (x *GetJobResponse) GetTotalCandidates() uint64 {
	if x != nil {
		return x.TotalCandidates
	}
	return 0
}

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_crypto_jobs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_jobs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_crypto_jobs_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_proto_crypto_jobs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_jobs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_crypto_jobs_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterWorkerResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type RequestRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRangeRequest) Reset() {
	*x = RequestRangeRequest{}
	mi := &file_proto_crypto_jobs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRangeRequest) ProtoMessage() {}

func (x *RequestRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_jobs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRangeRequest.ProtoReflect.Descriptor instead.
func (*RequestRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_crypto_jobs_proto_rawDescGZIP(), []int{6}
}

func (x *RequestRangeRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type RequestRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Start         uint64                 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	ShouldStop    bool                   `protobuf:"varint,4,opt,name=should_stop,json=shouldStop,proto3" json:"should_stop,omitempty"`
	HasRange      bool                   `protobuf:"varint,5,opt,name=has_range,json=hasRange,proto3" json:"has_range,omitempty"`
	TargetHash    string                 `protobuf:"bytes,6,opt,name=target_hash,json=targetHash,proto3" json:"target_hash,omitempty"`
	Charset       string                 `protobuf:"bytes,7,opt,name=charset,proto3" json:"charset,omitempty"`
	MinLength     uint32                 `protobuf:"varint,8,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	MaxLength     uint32                 `protobuf:"varint,9,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRangeResponse) Reset() {
	*x = RequestRangeResponse{}
	mi := &file_proto_crypto_jobs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRangeResponse) ProtoMessage() {}

func (x *RequestRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_jobs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRangeResponse.ProtoReflect.Descriptor instead.
func (*RequestRangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_crypto_jobs_proto_rawDescGZIP(), []int{7}
}

func (x *RequestRangeResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RequestRangeResponse) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *RequestRangeResponse) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *RequestRangeResponse) GetShouldStop() bool {
	if x != nil {
		return x.ShouldStop
	}
	return false
}

func (x *RequestRangeResponse) GetHasRange() bool {
	if x != nil {
		return x.HasRange
	}
	return false
}

func (x *RequestRangeResponse) GetTargetHash() string {
	if x != nil {
		return x.TargetHash
	}
	return ""
}

func (x *RequestRangeResponse) GetCharset() string {
	if x != nil {
		return x.Charset
	}
	return ""
}

func (x *RequestRangeResponse) GetMinLength() uint32 {
	if x != nil {
		return x.MinLength
	}
	return 0
}

func (x *RequestRangeResponse) GetMaxLength() uint32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

type ReportRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Start         uint64                 `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	Found         bool                   `protobuf:"varint,5,opt,name=found,proto3" json:"found,omitempty"`
	Plaintext     string                 `protobuf:"bytes,6,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRangeRequest) Reset() {
	*x = ReportRangeRequest{}
	mi := &file_proto_crypto_jobs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRangeRequest) ProtoMessage() {}

func (x *ReportRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_jobs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRangeRequest.ProtoReflect.Descriptor instead.
func (*ReportRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_crypto_jobs_proto_rawDescGZIP(), []int{8}
}

func (x *ReportRangeRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportRangeRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportRangeRequest) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ReportRangeRequest) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *ReportRangeRequest) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ReportRangeRequest) GetPlaintext() string {
	if x != nil {
		return x.Plaintext
	}
	return ""
}

type ReportRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ShouldStop    bool                   `protobuf:"varint,2,opt,name=should_stop,json=shouldStop,proto3" json:"should_stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRangeResponse) Reset() {
	*x = ReportRangeResponse{}
	mi := &file_proto_crypto_jobs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRangeResponse) ProtoMessage() {}

func (x *ReportRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_jobs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRangeResponse.ProtoReflect.Descriptor instead.
func (*ReportRangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_crypto_jobs_proto_rawDescGZIP(), []int{9}
}

func (x *ReportRangeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportRangeResponse) GetShouldStop() bool {
	if x != nil {
		return x.ShouldStop
	}
	return false
}

var File_proto_crypto_jobs_proto protoreflect.FileDescriptor

const file_proto_crypto_jobs_proto_rawDesc = "" +
	"\n" +
	"\x17proto/crypto_jobs.proto\x12\rcryptojobs.v1\"\xaa\x01\n" +
	"\x10CreateJobRequest\x12\x1f\n" +
	"\vtarget_hash\x18\x01 \x01(\tR\n" +
	"targetHash\x12\x18\n" +
	"\acharset\x18\x02 \x01(\tR\acharset\x12\x1d\n" +
	"\n" +
	"min_length\x18\x03 \x01(\rR\tminLength\x12\x1d\n" +
	"\n" +
	"max_length\x18\x04 \x01(\rR\tmaxLength\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\x04R\tchunkSize\"x\n" +
	"\x11CreateJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12)\n" +
	"\x10total_candidates\x18\x02 \x01(\x04R\x0ftotalCandidates\x12!\n" +
	"\ftotal_ranges\x18\x03 \x01(\x04R\vtotalRanges\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xcf\x02\n" +
	"\x0eGetJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vtarget_hash\x18\x02 \x01(\tR\n" +
	"targetHash\x12\x18\n" +
	"\acharset\x18\x03 \x01(\tR\acharset\x12\x1d\n" +
	"\n" +
	"min_length\x18\x04 \x01(\rR\tminLength\x12\x1d\n" +
	"\n" +
	"max_length\x18\x05 \x01(\rR\tmaxLength\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1c\n" +
	"\tplaintext\x18\a \x01(\tR\tplaintext\x12)\n" +
	"\x10completed_ranges\x18\b \x01(\x04R\x0fcompletedRanges\x12!\n" +
	"\ftotal_ranges\x18\t \x01(\x04R\vtotalRanges\x12)\n" +
	"\x10total_candidates\x18\n" +
	" \x01(\x04R\x0ftotalCandidates\"P\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"4\n" +
	"\x16RegisterWorkerResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"2\n" +
	"\x13RequestRangeRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\x8c\x02\n" +
	"\x14RequestRangeResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x04R\x03end\x12\x1f\n" +
	"\vshould_stop\x18\x04 \x01(\bR\n" +
	"shouldStop\x12\x1b\n" +
	"\thas_range\x18\x05 \x01(\bR\bhasRange\x12\x1f\n" +
	"\vtarget_hash\x18\x06 \x01(\tR\n" +
	"targetHash\x12\x18\n" +
	"\acharset\x18\a \x01(\tR\acharset\x12\x1d\n" +
	"\n" +
	"min_length\x18\b \x01(\rR\tminLength\x12\x1d\n" +
	"\n" +
	"max_length\x18\t \x01(\rR\tmaxLength\"\xa4\x01\n" +
	"\x12ReportRangeRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x04R\x03end\x12\x14\n" +
	"\x05found\x18\x05 \x01(\bR\x05found\x12\x1c\n" +
	"\tplaintext\x18\x06 \x01(\tR\tplaintext\"R\n" +
	"\x13ReportRangeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1f\n" +
	"\vshould_stop\x18\x02 \x01(\bR\n" +
	"shouldStop2\xb7\x03\n" +
	"\x10SchedulerService\x12N\n" +
	"\tCreateJob\x12\x1f.cryptojobs.v1.CreateJobRequest\x1a .cryptojobs.v1.CreateJobResponse\x12E\n" +
	"\x06GetJob\x12\x1c.cryptojobs.v1.GetJobRequest\x1a\x1d.cryptojobs.v1.GetJobResponse\x12]\n" +
	"\x0eRegisterWorker\x12$.cryptojobs.v1.RegisterWorkerRequest\x1a%.cryptojobs.v1.RegisterWorkerResponse\x12W\n" +
	"\fRequestRange\x12\".cryptojobs.v1.RequestRangeRequest\x1a#.cryptojobs.v1.RequestRangeResponse\x12T\n" +
	"\vReportRange\x12!.cryptojobs.v1.ReportRangeRequest\x1a\".cryptojobs.v1.ReportRangeResponseB#Z!tp-final-sdp/pkg/api/cryptojobsv1b\x06proto3"

var (
	file_proto_crypto_jobs_proto_rawDescOnce sync.Once
	file_proto_crypto_jobs_proto_rawDescData []byte
)

func file_proto_crypto_jobs_proto_rawDescGZIP() []byte {
	file_proto_crypto_jobs_proto_rawDescOnce.Do(func() {
		file_proto_crypto_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_crypto_jobs_proto_rawDesc), len(file_proto_crypto_jobs_proto_rawDesc)))
	})
	return file_proto_crypto_jobs_proto_rawDescData
}

var file_proto_crypto_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_crypto_jobs_proto_goTypes = []any{
	(*CreateJobRequest)(nil),       // 0: cryptojobs.v1.CreateJobRequest
	(*CreateJobResponse)(nil),      // 1: cryptojobs.v1.CreateJobResponse
	(*GetJobRequest)(nil),          // 2: cryptojobs.v1.GetJobRequest
	(*GetJobResponse)(nil),         // 3: cryptojobs.v1.GetJobResponse
	(*RegisterWorkerRequest)(nil),  // 4: cryptojobs.v1.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 5: cryptojobs.v1.RegisterWorkerResponse
	(*RequestRangeRequest)(nil),    // 6: cryptojobs.v1.RequestRangeRequest
	(*RequestRangeResponse)(nil),   // 7: cryptojobs.v1.RequestRangeResponse
	(*ReportRangeRequest)(nil),     // 8: cryptojobs.v1.ReportRangeRequest
	(*ReportRangeResponse)(nil),    // 9: cryptojobs.v1.ReportRangeResponse
}
var file_proto_crypto_jobs_proto_depIdxs = []int32{
	0, // 0: cryptojobs.v1.SchedulerService.CreateJob:input_type -> cryptojobs.v1.CreateJobRequest
	2, // 1: cryptojobs.v1.SchedulerService.GetJob:input_type -> cryptojobs.v1.GetJobRequest
	4, // 2: cryptojobs.v1.SchedulerService.RegisterWorker:input_type -> cryptojobs.v1.RegisterWorkerRequest
	6, // 3: cryptojobs.v1.SchedulerService.RequestRange:input_type -> cryptojobs.v1.RequestRangeRequest
	8, // 4: cryptojobs.v1.SchedulerService.ReportRange:input_type -> cryptojobs.v1.ReportRangeRequest
	1, // 5: cryptojobs.v1.SchedulerService.CreateJob:output_type -> cryptojobs.v1.CreateJobResponse
	3, // 6: cryptojobs.v1.SchedulerService.GetJob:output_type -> cryptojobs.v1.GetJobResponse
	5, // 7: cryptojobs.v1.SchedulerService.RegisterWorker:output_type -> cryptojobs.v1.RegisterWorkerResponse
	7, // 8: cryptojobs.v1.SchedulerService.RequestRange:output_type -> cryptojobs.v1.RequestRangeResponse
	9, // 9: cryptojobs.v1.SchedulerService.ReportRange:output_type -> cryptojobs.v1.ReportRangeResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_crypto_jobs_proto_init() }
func file_proto_crypto_jobs_proto_init() {
	if File_proto_crypto_jobs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_crypto_jobs_proto_rawDesc), len(file_proto_crypto_jobs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_crypto_jobs_proto_goTypes,
		DependencyIndexes: file_proto_crypto_jobs_proto_depIdxs,
		MessageInfos:      file_proto_crypto_jobs_proto_msgTypes,
	}.Build()
	File_proto_crypto_jobs_proto = out.File
	file_proto_crypto_jobs_proto_goTypes = nil
	file_proto_crypto_jobs_proto_depIdxs = nil
}
